window.addEventListener("load",()=>{const e=document.querySelector(".form"),t=document.querySelectorAll("#form input"),o=(document.querySelector("#textarea"),{name:/^[a-zA-ZÀ-ÿ\s]{1,40}$/,email:/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/}),r={name:!1,email:!1,textarea:!0},s=e=>{switch(console.log(e.target.name),e.target.name){case"name":c(o.name,e.target,"name")
break
case"email":c(o.email,e.target,"email")}},c=(e,t,o)=>{e.test(t.value)?(document.getElementById(`${o}`).classList.remove("grupo-incorrecto"),document.getElementById(`${o}`).classList.add("grupo-correcto"),document.querySelector(`#${o} i`).classList.add("fa-check-circle"),document.querySelector(`#${o} i`).classList.remove("fa-times-circle"),document.querySelector(`#${o} .input-error`).classList.remove("input-error-activo"),r[o]=!0):(document.getElementById(`${o}`).classList.add("grupo-incorrecto"),document.getElementById(`${o}`).classList.remove("grupo-correcto"),document.querySelector(`#${o} i`).classList.add("fa-times-circle"),document.querySelector(`#${o} i`).classList.remove("fa-check-circle"),document.querySelector(`#${o} .input-error`).classList.add("input-error-activo"),r[o]=!1)}
t.forEach(e=>{e.addEventListener("keyup",s),e.addEventListener("blur",s)}),e.addEventListener("submit",e=>{r.name&&r.email&&""==!e.target.name.value&&""==!e.target.email.value&&""==!e.target.textarea.value?(document.getElementById("mensaje-exito").classList.add("mensaje-exito-activo"),setTimeout(()=>{document.getElementById("mensaje-exito").classList.remove("mensaje-exito-activo")},4e3),document.querySelectorAll(".grupo-correcto").forEach(e=>{e.classList.remove("grupo-correcto")})):(document.getElementById("mensaje").classList.add("mensaje-activo"),setTimeout(()=>{document.getElementById("mensaje").classList.remove("mensaje-activo")},4e3))})
const a=document.querySelector(".btn-navToggle"),n=document.querySelector(".ul-responsive"),i=()=>{let e=document.querySelector(".btn-navToggle i"),t=document.querySelectorAll(".nav-responsive ul")
t.forEach(t=>{"ul-responsive ul-responsive-visible"===t.classList.value?(e.classList.remove("fa-bars"),e.classList.add("fa-times")):(e.classList.remove("fa-times"),e.classList.add("fa-bars"))})}
a.addEventListener("click",()=>{n.classList.toggle("ul-responsive-visible"),i()})
const l=document.querySelector("#home"),d=document.querySelector("#about"),m=document.querySelector("#portfolio"),u=document.querySelector("#skills"),v=document.querySelector("#contact"),g=()=>{n.classList.remove("ul-responsive-visible"),i()}
l.addEventListener("click",g),d.addEventListener("click",g),m.addEventListener("click",g),u.addEventListener("click",g),v.addEventListener("click",g)
const y=document.querySelector(".general"),L=document.querySelector(".progressCircle"),p=document.querySelector(".spanScroll")
let S=L.r.baseVal.value,q=2*S*Math.PI
L.style.strokeDasharray=q
const E=e=>{L.style.strokeDashoffset=q-e/100*q}
0===window.scrollY&&E(0),window.onscroll=(()=>{containerHeight=y.offsetHeight-window.innerHeight,containerPosition=y.getBoundingClientRect().top,progressPercentage=(containerHeight+containerPosition)/containerHeight*100,cssWidth=100-Math.ceil(progressPercentage),p.innerHTML=`${cssWidth}%`,E(cssWidth)})})
